### ISSUE TITLE
Find/Avoid exploring no-source

### ISSUE THREAD

**Issue by Owlz** [S2E/docs#15]
Having the darndest time installing. However, once I get it installed I am curious how to perform "find/avoid" strategies with s2e.

It seems that if you have source you could add terminating instructions on paths you didn't want to ever take and print out solutions on the paths you wanted. However, without source, is there a good way to do that? Something akin to giving S2E a list of 1 or more "good" IP addresses (print out solution there and exit), and "bad" IP addresses (if S2E hits those, discard that path).

**Comment by Epeius** [comment]
Hi Owlz,

In order to perform "find/avoid" strategy in s2e when testing binaries, you need to define your own "good" and "bad" paths, then you can choose which path (also known as state) to terminate by writing your own searcher plugin. 

-Bin

**Comment by Owlz** [comment]
Totally get that I would need to define my own good and bad. However, is
there an example of how this might look as a searcher? Also, given it could
be generic enough to work in many cases, is there thought to making it one
of the base plugins that comes with s2e?

**Comment by Epeius** [comment]
Since s2e is implemented on top of klee, it would be better to understand how klee's searcher works first. Also in s2e, we have implemented some searchers for different purpose (e.g.,  testing cgc binaries). You can find such plugins in libs2eplugins repo. You may also want to have a look at the basic implementation of a RandomSearcher before writing your own searchers.

-Bin
