### ISSUE TITLE
Inaccuracies in Writing Plugins doc

### ISSUE THREAD

**Issue by Owlz** [S2E/docs#18]
After beating my head on the wall for a little while, I found there's a few inaccuracies in your plugin writing page:

https://github.com/S2E/docs/blob/master/src/Howtos/WritingPlugins.rst

Namely:

It tells you to include the following:
```c
#include <s2e/Plugins/CorePlugin.h>
```
This appears to not be accurate anymore. The real path appears to be:
```c
#include <s2e/CorePlugin.h>
```

Also, it doesn't tell you to include the util.h, which is where "hexval" function lives, thus more compile errors.

```c
#include <s2e/Utils.h>
```

There also doesn't appear to be direct information about how to re-compile to add in your new code. Likely, re-compiling all of S2E to simply update your small plugin would be a waste. Also, since I compiled initially using the s2e build script, i don't have the exact line that was used handy. However, I've worked out the following line which seems to work:

```
cd build/s2e
CMAKE_PREFIX_PATH=llvm-release/cmake/modules/CMakeFiles:/home/s2e/s2e/source/s2e/libs2eplugins S2EPREFIX=/home/s2e/s2e/install make -f ../../source/s2e/Makefile install
```

Obviously, adjust for your own install path. But, for laymen like me who aren't familiar with S2E, having a re-compile line or information such as that available would be useful.

**Comment by Owlz** [comment]
Would be helpful to have a `s2e rebuild` or something, to attempt to keep the compiled work where you can but also take care of the details of what path things are being installed into.

**Comment by adrianherrera** [comment]
Hi Owlz,

These are all great points! Many thanks for pointing these out; this is why it's helpful to have fresh eyes reading this stuff. I'll see that the "Writing a Plugin" tutorial gets updated.

BTW I'm also working on a new tutorial at https://github.com/S2E/docs/blob/improvement/ctf-tutorial/src/Tutorials/CTF.rst. It's not yet complete and will likely need a few revisions, but feel free to have an early look because as a newcomer you might read things that seem perfectly obvious to us but are in fact, not obvious at all.

Yes, I think having a relook at `s2e build` is a good idea. I have a few ideas around this for rebuilding specific S2E components, I just haven't got around to implementing any of them yet.

Thanks for this issue!

~Adrian

**Comment by adrianherrera** [comment]
P.S. I hope the head's okay ;)

**Comment by Owlz** [comment]
Hey! So that write-up you mentioned is super helpful. A few questions came to my mind reading it:

1. You explain how to narrow down the search to our exe. What if we wanted to narrow down to a dll inside an exe?
1. How to handle PIE addresses?
1. Constraining symbolic variables if input via stdin or other pseudofile?

Thanks!

**Comment by Owlz** [comment]
Btw, you have a bit of a compile error in your write as states:

```c
namespace se2 {
```

Ran into that gem when compiling. Sadly it took me a little while to realize the order was wrong myself!

**Comment by adrianherrera** [comment]
Thanks! Those are all great questions, and probably warrant another tutorial (for which I don't really have time for right now, unfortunately). So I'll answer them quickly here:

1. If you want to narrow down to a specific DLL within a process' address space, you can use the `ModuleMap` plugin. You can see an example of how to do this here -> https://github.com/S2E/libs2eplugins/pull/7 (not yet merged)
2. You can register for a moduleLoad event and get the base address of the module that you are interested in (or use the `ModuleMap` plugin). Then you'll have to do some offset calcs yourself to get the address that you want
3. Same approach. Register for `onSymbolicVariableCreation` events and wait for your specific variable to be created. It doesn't matter if it's a file or a string or a buffer or whatever, creating a symbolic variable will always trigger this event. Then you can apply your constraints as usual.

**Comment by Owlz** [comment]
Ok, so i think i've got the onModuleLoad part working(ish). However, it appears to only contain the base module, not the loaded libraries for it. From your ModuleMap examples, that seems to be more focused on figuring out what is actually being called at run time. I feel like my use case is actually a bit simpler, as I just wish to figure out what the base address is when it gets loaded, and perform static calculations off of that. Can I do that with the ModuleDescriptor object that gets returned from onModuleLoad?

Thanks again for all the help in this!

**Comment by adrianherrera** [comment]
Ah actually, are you running a Linux ELF? If so, you are correct - see https://github.com/S2E/libs2eplugins/blob/master/src/s2e/Plugins/OSMonitors/Linux/LinuxMonitor.cpp#L191 :) 

In theory this method should create the `ModuleDescriptor` object as you described. However it's not implemented yet, due to not enough time :(

However, if you are running with s2e.so (which you should be if you use the default bootstrap script), then you should see a mesage in your debug.txt that lists the addresses of the loaded modules when your target process is created. Hopefully this will help some-what.

You're welcome!

**Comment by Owlz** [comment]
Yep. I've been looking at ELF files primarily. Good to know it's not just me.

Also, been using the following:

```c
if (!m_procDetector->isTracked(state)) {
```

To check if i'm in my correct process. However, this check doesn't seem to be working for ELF binaries that are position independent. Basically it's just always coming back false. Works fine when it's not PIE.

**Comment by adrianherrera** [comment]
Hmm interesting. Could you please create a new issue in the libs2eplugins
repo as a bug. That way someone can look at it at some point...

**Comment by adrianherrera** [comment]
I think this one is all fixed now.
