### ISSUE TITLE
kvm in qemu failing

### ISSUE THREAD

**Issue by bannsec** [S2E/docs#22]
So I've been playing with a test C binary:

```c
#include <stdio.h>
#include <string.h>
 
int main() {
    char buf[32];
 
    fgets(buf, 32, stdin);
 
    if (strstr(buf, "winner") == buf) {
        printf("Win!");
    }
 
    return 0;
}
```

My hope was that I could get S2E to execute to the "win" state. However, so far it has not been able to even get past fgets (with symbolic input). Part of what I have discovered is that kvm has been silently failing for QEMU. After querying around a while, I found the error code and some discussion on it:

https://askubuntu.com/questions/252452/qemu-hardware-error-0x80000021

I ran QEMU with increased memory (I brought it up to 1024M) and kvm was able to kick in. Unfortunately, I couldn't do this with the base saved vm image since it was saved with 256M.

This leads me to a couple things:

1. Perhaps QEMU should have some build-in monitoring to detect if it has failed to utilize kvm. My guess is this fail happens more often than you might expect and people new to S2E (such as myself) wouldn't necessarily know that right away.
2. Definitely should be something in documentation on this being a possibility and how to check for KVM failing/how to fix it.
3. Maybe think about upping the default memory size for the saved VM. I understand there's a tradeoff with memory there, but having kvm successfully utilized would greatly improve performance.

**Comment by Owlz** [comment]
Investigating this some more. Oddly enough, it might have to do with the LD_PRELOAD...

```bash
LD_PRELOAD=/home/s2e/s2e/install/share/libs2e/libs2e-x86_64-s2e.so
```

Haven't been able to get errors out of it, however with the preload qemu will not load up kvm, without the preload it will load up kvm.

**Comment by adrianherrera** [comment]
Hey Owlz,

Thanks for this. This is interesting - I have never encountered this
before. Just to make things clear, this isn't a "real" KVM - we just reuse
the interface/API to separate QEMU and S2E. So what may be an issue in
actual KVM may not be applicable here.

Regardless, could you please do me a favour. If you haven't ready, update
s2e-env so that you get the latest version with the import/export commands.
Then export the project and upload it to the Google group (this will also
be a good test for import/export!).

I'm away for a week at a workshop, so I won't be able to look at it until
Monday week at the earliest.

Regards,
Adrian

**Comment by Owlz** [comment]
Will do. Given its not a real kvm, does that mean you're not expecting
/dev/kvm to actually be mounted from the running qemu? Is the pseudo kvm
providing performance benefits or just a gateway for commands?

**Comment by Owlz** [comment]
Side note, I still haven't been accepted to group lol

**Comment by vitalych** [comment]
S2E doest not expect /dev/kvm to actually exist. You can run it inside a VM if you want. libs2e.so intercepts open() syscall and emulates the kvm behavior. In the future, we'll probably have some support to switch between real kvm and the emulated kvm. The real one will provide native execution speeds for concrete code while the emulated one will do symbolic execution.

**Comment by vitalych** [comment]
By the way, we expect users to launch s2e with the scripts generated by s2e-env. You have to be extra careful if you want to do it manually as it is easy to use wrong parameters.

**Comment by Owlz** [comment]
Yeah. The reason I was running the line manually was because it has been impossibly slow for me so I was attempting to figure out why. Now that you mention S2E is hooking open calls to kvm, I can stop my search into why kvm isn't being used lol..

Still trying to figure out why S2E has not been able to execute past the very first `fgets` call. How long should it usually take for S2E to execute through an `fgets` call anyway?

**Comment by Owlz** [comment]
Can someone let me know if `fgets` is too complicated for S2E to parse? I let it run for an hour or so and it basically just chewed up gigs of memory and never made it past the `fgets` call above.

**Comment by adrianherrera** [comment]
There is currently an issue with clocks that can cause S2E to hang when performing symbex. I have 80% of a fix in branches across various repos, but there is still a problem with my fix that I need to debug before I can make a PR. This _may_ be the issue (but without having a look myself I cannot confirm 100%)

Unfortunately I won't have time to look at it until I return home next week.

**Comment by adrianherrera** [comment]
P.S. you should have access to the forum now. Sorry for the delay.

**Comment by Owlz** [comment]
Happy to be a guinea pig for proposed changes. I have run into the S2E freezing issue on most example code I have run.

**Comment by adrianherrera** [comment]
Hey @owlz, sorry, I haven't had time to get back to this. I'll let you know once I've finished ironing out the last few kinks.

**Comment by Stormys** [comment]
Is there any updates to this? I believe I have been running into S2E hanging as well.

**Comment by adrianherrera** [comment]
Hi @Owlz and @Stormys,

I finally had a chance to look at this again. I've made a number of PRs that I _think_ fixes the issue. They are:

* https://github.com/S2E/libs2e/pull/6
* https://github.com/S2E/libcpu/pull/3
* https://github.com/S2E/qemu/pull/5
* https://github.com/S2E/libs2ecore/pull/5

All of the branches are called `improvement/clock-share`, so you may be able to use repo to check them out all at once.

If you're interested, please check out the `improvement/clock-share` branches and rebuild S2E (`s2e build -r qemu libs2e` should do the trick for a release build) and try it out. Please post any feedback here. Note that they'll need to go through the standard review process, so they might be sitting around unmerged for a little while, depending on how stupid my solution is :)

~Adrian

**Comment by Owlz** [comment]
Adrian,

Had a chance to try this out, however I'm having difficulty getting to an answer. The main reason, I think, is that XMM isn't supported. So I've been trying to work around that by compiling against musl (then installing musl in the VM before running). However, when I do that, the program seems to veer off course immediately and exit.

It does appear that a statically compiled binary with lib musl will execute through the fgets as above. So that's encouraging.

The XMM stuff we're tracking elsewhere. However, do you have any idea why musl appears to cause issues with S2E? I do apt-get install it into the VM using bootstrap.sh before executing the binary.

Here's some debug.txt output from the musl dynamically compiled one:

```
132 [State 0] LinuxMonitor: Process ./s2ecmd loaded entry_point=0x7f32e92ae190 pid=0x531 start_code=0x400000 end_code=0x402c6c start_data=0x602e10 end_data=0x6030f0 start_stack=0x7fffed584e50
132 [State 0] LinuxMonitor: ModuleDescriptor Name=s2ecmd Path=./s2ecmd NativeBase=0x400000 LoadBase=0x400000 Size=0x2030f0 AddressSpace=0xd710000 Pid=0x531 EntryPoint=0x7f32e92ae190 Checksum=0xf3630810
132 [State 0] ModuleExecutionDetector: Module s2ecmd loaded - Base=0x400000 NativeBase=0x400000 Size=0x2030f0 AS=0xd710000
132 [State 0] ModuleExecutionDetector: 
132 [State 0] LinuxMonitor: Process ././test loaded entry_point=0xffff88000e3e7aa8 pid=0x532 start_code=0x400000 end_code=0x4f1bf4 start_data=0x6f1de0 end_data=0x6fae48 start_stack=0x7ffce7644fb0
132 [State 0] ProcessExecutionDetector: starting to track: test (pid: 0x532 as: 0xd720000)
132 [State 0] LinuxMonitor: ModuleDescriptor Name=test Path=././test NativeBase=0x400000 LoadBase=0x400000 Size=0x2fae48 AddressSpace=0xd720000 Pid=0x532 EntryPoint=0xffff88000e3e7aa8 Checksum=0xf3630810
132 [State 0] ModuleExecutionDetector: Module test loaded - Base=0x400000 NativeBase=0x400000 Size=0x2fae48 AS=0xd720000
132 [State 0] ModuleExecutionDetector:  [REGISTERING ID=mod_0]
132 [State 0] ProcessExecutionDetector: Unloading process 0x532
132 [State 0] ModuleExecutionDetector: Process 0x1e08000 is unloaded
132 [State 0] LinuxMonitor: Removing task (pid=0x532, cr3=0xd720000, exitCode=32512) record from collector.
132 [State 0] BaseInstructions: Inserted symbolic data @0x11a9010 of size 0x10: buffer pc=0x4010c9
132 [State 0] ProcessExecutionDetector: Unloading process 0x531
132 [State 0] ModuleExecutionDetector: Process 0x1e08000 is unloaded
132 [State 0] LinuxMonitor: Removing task (pid=0x531, cr3=0xd710000, exitCode=13) record from collector.
132 [State 0] LinuxMonitor: Process ./s2ecmd loaded entry_point=0x7f97799c8190 pid=0x533 start_code=0x400000 end_code=0x402c6c start_data=0x602e10 end_data=0x6030f0 start_stack=0x7ffcda09fc00
132 [State 0] LinuxMonitor: ModuleDescriptor Name=s2ecmd Path=./s2ecmd NativeBase=0x400000 LoadBase=0x400000 Size=0x2030f0 AddressSpace=0xd68c000 Pid=0x533 EntryPoint=0x7f97799c8190 Checksum=0xf3630810
132 [State 0] ModuleExecutionDetector: Module s2ecmd loaded - Base=0x400000 NativeBase=0x400000 Size=0x2030f0 AS=0xd68c000
132 [State 0] ModuleExecutionDetector: 
132 [State 0] BaseInstructions: Killing state 0
132 [State 0] Terminating state early: State was terminated by opcode
            message: "'test' state killed"
            status: 0x7f
132 [State 0] TestCaseGenerator: generating test case at address 0x400eed
132 [State 0] TestCaseGenerator:          v0_buffer_0 = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}; (string) "................"
All states were terminated
Terminating node 0 (instance slot 0)
```

**Comment by adrianherrera** [comment]
Hey!!

Good to hear that the clock issue _appears_ to be resolved!

Is there any output in the serial.txt file? Your program is exiting with
error code 127, which generally means "command not found". Is there some
file that's not being correctly uploaded to the guest?

**Comment by Owlz** [comment]
Good call! Yeah, so it turns out that my musl install commands weren't working. Instead, I just S2EGET copied up the deb pkg and installed it that way. Now, executing through the fgets system call in musl appears to work. Obviously hard to tell all the implications of the code change, but that use case went from freezing up to actually executing. Seems like a good thing!

**Comment by adrianherrera** [comment]
Hey @bannsec, is this closable?

**Comment by bannsec** [comment]
@adrianherrera , I think so! My original issue appears to work without problem now. You rock!
